version: "3.9"

services:
  http:
    image: nginx:latest
    container_name: HTTP
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - script
      - data
    networks:
      - web

  script:
    build: .
    image: php-mysqli:latest
    container_name: SCRIPT
    volumes:
      - ./app:/app
    networks:
      - web

  data:
    image: mariadb:latest
    container_name: DATA
    environment:
      MARIADB_ROOT_PASSWORD: respons
    volumes:
      - ./db-sql:/docker-entrypoint-initdb.d:ro
    networks:
      - web

networks:
  web:
    driver: bridge
